version: '2.2'

services:
  openhab3:
    image: "openhab/openhab:3.0.0"
    container_name: openhab3
    restart: unless-stopped
    networks:
      - default
    ports:
      - "38080:8080/tcp" # http
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/var/docker/openhab3/addons:/openhab/addons"
      - "/var/docker/openhab3/conf:/openhab/conf"
      - "/var/docker/openhab3/userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
      USER_ID: "1000"
      GROUP_ID: "1000"

  oh3persistence-db:
    image: mariadb
    container_name: openhab3-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW
    ports:
      - "33306:3306"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/openhab3/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MeinOHrootPW2 # Datenbank Passwort wählen
      - MYSQL_PASSWORD=MeinOHPW2 # Datenbank Passwort wählen, wird bei der Nextcloudinstallation abgefragt
      - MYSQL_DATABASE=openhab3
      - MYSQL_USER=openhab3
      - MYSQL_INITDB_SKIP_TZINFO=1 # Behebt die bekannten Startprobleme der Datenbank


networks:
  default:
